### PR TITLE
First version of universal readme

### PR DESCRIPTION
**Pull request by khaosdoctor**
This is a first version @darlanmendonca @WendellAdriel 

What you guys think?

### CODE REVIEW

**Comment by WendellAdriel** [comment]
I liked!!!

**Comment by odineiramone** [comment]
Nice! When this first version was merged, I can translate into portuguesse

**Comment by darlanmendonca** [comment]
perfect!!

**Comment by khaosdoctor** [comment]
Thanks for the correction! @darlanmendonca

**Comment by darlanmendonca** [comment]
:D

**Pull request merged**
